### ISSUE TITLE
Implement Observe Func

### ISSUE THREAD

**Issue by fahedouch** [multicloudlab/crossplane-provider-ansible#10]
### What problem are you facing?

Like other Crossplane providers, Ansible provider should observe External Resource and save its observations in `managed.ExternalObservation`  than send it to the Reconciler.

I think that we can check  wether the managed ressource is `ResourceUpToDate` using `ansible-playbook --diff --check`

PS : our `ansible-playbook` sdk  github.com/apenella/go-ansible/pkg/playbook natively support `diff` and `check`  option https://pkg.go.dev/github.com/apenella/go-ansible/pkg/playbook#pkg-constants

**Comment by morningspace** [comment]
@fahedouch FYI: I logged an issue in Ansible community while ago, and they had the same suggestion using diff, https://github.com/ansible/ansible/issues/75248, but that has limitations.

**Comment by fahedouch** [comment]
Hey @morningspace ,

Yes I faced this limitation with shell tasks ( `--check` is not able to detect changes) . I think we should warn users of cases where the check is not effective by `ansible-playbook`

**Comment by fahedouch** [comment]
related ticket https://github.com/multicloudlab/crossplane-provider-ansible/issues/18

**Comment by fahedouch** [comment]
fixed by https://github.com/multicloudlab/crossplane-provider-ansible/pull/57
