### ISSUE TITLE
after to re apply a playbook, no change triggered 

### ISSUE THREAD

**Issue by a1h8** [multicloudlab/crossplane-provider-ansible#18]
### What happened?

no change detected 

### How can we reproduce it?
1/  apply a playbookset-inline
2/  change playbookset-inline 
3/  re apply this playbook

**Comment by fahedouch** [comment]
@morningspace @huang-cn waiting for observe func :)

**Comment by fahedouch** [comment]
fixed by https://github.com/multicloudlab/crossplane-provider-ansible/pull/57
