### ISSUE TITLE
CI/unit tests fail

### ISSUE THREAD

**Issue by fahedouch** [multicloudlab/crossplane-provider-ansible#25]
### What happened?

CI fail for the lack of `ansible-runner` and `ansible-galaxy` in CI : [CI / unit-tests ](https://github.com/multicloudlab/crossplane-provider-ansible/runs/5820503075?check_suite_focus=true#step:9:23)
We should create a docker image with necessary tooling for CI

### How can we reproduce it?

launch CI 

### What environment did it happen in?
Crossplane version:  None

**Comment by morningspace** [comment]
@fahedouch Can we mock it. I see https://github.com/crossplane-contrib/provider-terraform is using mock stuff.

**Comment by fahedouch** [comment]
@morningspace  it is not the same. Terraform mock `init` func when testing the workspace controller. but here I want to unitary test the `init` func

**Comment by fahedouch** [comment]
@morningspace  Makes sense, I'll fix that

**Comment by fahedouch** [comment]
fixed by https://github.com/multicloudlab/crossplane-provider-ansible/pull/55
